// Optional documentation build: node scripts/build-audit.mjs [marked ES-module path]
// The generated website has no dependency on marked at runtime.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {marked}=await import(process.argv[2]||'marked');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const parts=[
  ['accountability','Accountability & current build','docs/ACCOUNTABILITY-AUDIT.md'],
  ['dossier','Appendix A · full dossier','docs/audit/dossier-audit.md'],
  ['source','Appendix B · prior live website','docs/audit/SOURCE-AUDIT-v08.md'],
  ['intermediate','Appendix C · intermediate rebuild','docs/audit/NEW-SOURCE-AUDIT-v09.md']
];
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let combined='',body='';
for(const[id,title,file]of parts){
  const markdown=fs.readFileSync(path.join(root,file),'utf8');
  combined+='\n\n---\n\n# '+title+'\n\n'+markdown;
  const html=marked.parse(markdown,{gfm:true}).replace(/<table>/g,'<div class="table-scroll" tabindex="0" role="region" aria-label="Detailed findings table"><table>').replace(/<\/table>/g,'</table></div>');
  body+=`<section id="${id}"><p class="section-label">${escape(title)}</p>${html}</section>`;
}
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102b30"><title>AWE · The complete project audit</title><link rel="icon" href="./assets/mark.svg"><style>
:root{color-scheme:dark;font-family:system-ui,-apple-system,sans-serif;background:#10282d;color:#dde5de;line-height:1.72}*{box-sizing:border-box}body{margin:0}a{color:#efd19b;text-underline-offset:4px}a:focus-visible,[tabindex]:focus-visible{outline:2px solid #efd19b;outline-offset:5px}.topbar{position:sticky;top:0;z-index:3;background:#10282df5;border-bottom:1px solid #8daea533;display:flex;align-items:center;justify-content:space-between;padding:18px 5vw;gap:20px;backdrop-filter:blur(12px)}.brand{font:24px Georgia;letter-spacing:5px;text-decoration:none}.topbar span{font-size:13px;color:#b6cbc4}.topbar .return{font-size:14px}.layout{display:grid;grid-template-columns:230px minmax(0,1000px);gap:55px;max-width:1420px;margin:0 auto;padding:55px 40px 100px}.nav{position:sticky;top:120px;align-self:start;font-size:14px}.nav p,.section-label{font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#dbbb86}.nav a{display:block;margin:15px 0;text-decoration:none}.nav a:hover{text-decoration:underline}.nav .download{border-top:1px solid #97b5aa33;padding-top:20px;margin-top:25px}main{min-width:0}section{scroll-margin-top:105px;margin-bottom:95px;border-bottom:1px solid #adc5b02b;padding-bottom:55px}h1{font:clamp(32px,4vw,52px)/1.15 Georgia;color:#f1e4c9;margin:12px 0 28px;letter-spacing:-.5px}h2{font:29px/1.25 Georgia;color:#ecdcbb;margin:48px 0 18px}h3{font-size:19px;color:#ead3a6;margin:28px 0 12px}p{margin:0 0 18px}strong{color:#f2e5ca}ol,ul{padding-left:24px}li{margin-bottom:13px;padding-left:4px}code{font:13px/1.5 ui-monospace,SFMono-Regular,monospace;background:#7e9f8b19;padding:2px 4px;border-radius:3px;overflow-wrap:anywhere}pre{white-space:pre-wrap;background:#081e2480;padding:20px;overflow:auto}.table-scroll{overflow-x:auto;margin:26px 0;border:1px solid #9cbdad38;border-radius:5px}table{border-collapse:collapse;font-size:14px;line-height:1.6;width:100%;min-width:640px}th{text-align:left;background:#244038;color:#f0d6a3;font-size:13px}th,td{padding:14px 16px;border-bottom:1px solid #8baca42b;vertical-align:top}tr:nth-child(even){background:#a4c4b107}td:first-child{color:#efd5a7}blockquote{border-left:3px solid #b9a678;padding-left:20px;margin-left:0;color:#bfd1c7}hr{border:0;border-top:1px solid #97b5aa33;margin:35px 0}.footer{color:#a4bdb3;font-size:13px;padding-top:20px}@media(max-width:950px){.layout{grid-template-columns:1fr;padding:25px 24px;gap:20px}.nav{position:static;display:flex;flex-wrap:wrap;gap:8px 22px;border-bottom:1px solid #97b5aa33;padding-bottom:20px}.nav p{width:100%;margin:0}.nav a{margin:4px 0}.nav .download{padding:0;margin:4px 0;border:0}.topbar{padding:15px 24px}.topbar span{display:none}h1{font-size:37px}h2{font-size:26px}}@media print{.topbar,.nav{display:none}.layout{display:block;padding:0}:root{background:#fff;color:#222}h1,h2,h3,strong,td:first-child{color:#111}table{min-width:0;font-size:10px}.table-scroll{overflow:visible}a{color:#164e56}section{margin-bottom:30px}}
</style></head><body><header class="topbar"><a class="brand" href="./play.html">A W E</a><span>THE LIVING CONCORD · ACCOUNTABILITY RECORD</span><a class="return" href="./play.html">Return to the game ↗</a></header><div class="layout"><nav class="nav" aria-label="Audit sections"><p>The complete record</p>${parts.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('')}<a class="download" href="./audit.md" download="AWE_Complete_Audit.md">Download the full audit ↓</a></nav><main>${body}<p class="footer">Prepared from the recovered project, visible conversation and versioned source. Historical findings are not automatically current defects. No inaccessible chat transcript or completed production MMORPG is claimed.</p></main></div></body></html>`;
fs.writeFileSync(path.join(root,'public/audit.html'),page);
fs.writeFileSync(path.join(root,'public/audit.md'),combined.trim()+'\n');
console.log(JSON.stringify({sections:parts.length,markdownBytes:Buffer.byteLength(combined),htmlBytes:Buffer.byteLength(page)}));
