"""Reproducible V/50 compilation. Source fields retain their published precision.
The IAU names annotate HR entries; their component positions never replace BSC
astrometry. No absent proper motion is silently represented as a measurement.
"""
from pathlib import Path
import gzip, hashlib, json, re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data/sky'
raw = (DATA / 'bsc5.dat').read_bytes() if (DATA / 'bsc5.dat').exists() else gzip.decompress((DATA / 'bsc5.dat.gz').read_bytes())
names_raw = (DATA / 'iau-csn-2022.txt').read_bytes()
names = {}
for line in names_raw.decode().splitlines():
    if line.startswith(('#', '$')) or not re.search(r'\d{4}-\d\d-\d\d', line):
        continue
    hr = re.match(r'HR\s+(\d+)\s*$', line[35:48].strip())
    if hr:
        names.setdefault(int(hr[1]), []).append(line[18:35].strip())

def number(s):
    return float(s) if s.strip() else None

rows, omitted = [], []
for line in raw.decode('ascii').splitlines():
    hr = int(line[:4])
    if not line[75:90].strip():
        omitted.append(hr)
        continue
    ra = 15 * (int(line[75:77]) + int(line[77:79])/60 + float(line[79:83])/3600)
    dec = (int(line[84:86]) + int(line[86:88])/60 + int(line[88:90])/3600) * (-1 if line[83] == '-' else 1)
    rows.append([hr, line[4:14].strip(), round(ra, 9), round(dec, 9), number(line[102:107]),
                 number(line[109:114]), number(line[148:154]), number(line[154:160]),
                 line[127:147].strip(), names.get(hr, [])])
assert len(rows) == 9096 and len(omitted) == 14
assert len({r[0] for r in rows}) == len(rows)
assert all(0 <= r[2] < 360 and -90 <= r[3] <= 90 and r[4] is not None for r in rows)
meta = {
    'id': 'yale-bsc5-cds-v50-20260913', 'title': 'Yale Bright Star Catalogue, 5th Revised Edition (Hoffleit & Warren)',
    'source': 'https://cdsarc.cds.unistra.fr/ftp/V/50/', 'accessed': '2026-09-13',
    'frame': 'FK5 J2000, epoch 2000.0', 'count': len(rows), 'omittedHR': omitted,
    'fields': ['HR', 'designation', 'raDegrees', 'decDegrees', 'Vmag', 'BminusV', 'pmRAcosDecArcsecYr', 'pmDecArcsecYr', 'spectralType', 'IAUnames'],
    'names': {'source': 'https://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt', 'edition': '2022-04-04', 'license': 'Creative Commons Attribution, per source header',
              'note': 'Pinned historical naming table; newer IAU adoptions exist. Names can identify a component of a BSC multiple system.'},
    'sha256': {'bsc5.dat': hashlib.sha256(raw).hexdigest(), 'iau-csn-2022.txt': hashlib.sha256(names_raw).hexdigest()},
    'model': 'First-order tangent proper motion; precession and nutation. No stellar parallax, annual aberration, radial perspective acceleration, binary or variability model. B-V colors are illustrative.'
}
out = '// Generated by scripts/build-sky-catalog.py. See data/sky and /sky-guide.html for attribution.\n'
out += 'export const CATALOG_META = '+json.dumps(meta, ensure_ascii=False, separators=(',', ':'))+';\n'
out += 'export const CATALOG_ROWS = '+json.dumps(rows, ensure_ascii=False, separators=(',', ':'))+';\n'
(ROOT/'public/sky-catalog.js').write_text(out)
(DATA/'manifest.json').write_text(json.dumps(meta, ensure_ascii=False, indent=2)+'\n')
(DATA/'bsc5.dat.gz').write_bytes(gzip.compress(raw, mtime=0))
print(json.dumps({'stars': len(rows), 'namedHR': len(names), 'omitted': omitted, 'javascriptBytes': len(out.encode())}))
